version: '3'

services:

  db:
    image: mysql:5.7    
    command: --innodb-use-native-aio=0
    container_name: db    
    restart: always    
    tty: true    
    volumes:      
      - ./mysqldb:/var/lib/mysql    
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - nodenet

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: fabiocordeiroaraujo/node
    container_name: app
    networks: 
      - nodenet
    tty: true    
    ports:
      - "3000:3000"        
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 300s -wait-retry-interval 30s ./start.sh"
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: fabiocordeiroaraujo/nginx:prod
    container_name: nginx
    networks:
     - nodenet
    ports:
     - "8080:80"
    depends_on:
     - app

networks:
  nodenet:
    driver: bridge